function [cfg_artifact] = coSMIC_mergeThArtResults(cfg_artifact1, cfg_artifact2)
% coSMIC_MERGEARTIFACTRESULTS is a functions which merges two artifact
% specification structures into on common one. These function is useful,
% when e.g. for certain channels (V1, V2) another threshold value has to be
% used.
%
% Use as
%   [cfg_artifact] = coSMIC_mergeThArtResults(cfg_artifact1, cfg_artifact2)
%
% where the input data elements has to be a result of coSMIC_AUTOARTIFACT
%
% This function requires the fieldtrip toolbox.
%
% See also coSMIC_AUTOARTIFACT

% Copyright (C) 2019, Daniel Matthes, MPI CBS

% -------------------------------------------------------------------------
% check input - only threshold artifacts should be merged
% -------------------------------------------------------------------------
if ~isfield(cfg_artifact1.mother.artfctdef, 'threshold') || ...
    ~isfield(cfg_artifact1.child.artfctdef, 'threshold')
  error('cfg_artifact1 has no threshold artifacts. Nothing to merge.');
end

if ~isfield(cfg_artifact2.mother.artfctdef, 'threshold') || ...
    ~isfield(cfg_artifact2.child.artfctdef, 'threshold')
  error('cfg_artifact2 has no threshold artifacts. Nothing to merge.');
end

% test if both artifact specification structures were generated by using
% the same dataset
if size(cfg_artifact1.mother.artfctdef.threshold.trl, 1) ~= ...
    size(cfg_artifact2.mother.artfctdef.threshold.trl, 1)
  error(['The input structures have different trl specifications. '...
          'Merging is not possible!']);
end

% -------------------------------------------------------------------------
% merge input structures
% -------------------------------------------------------------------------
cfg_artifact = cfg_artifact1;

cfg_artifact.mother.artfctdef.threshold = removefields( ...
  cfg_artifact.mother.artfctdef.threshold, {'channel', 'range', 'artifact'});

cfg_artifact.child.artfctdef.threshold = removefields( ...
  cfg_artifact.child.artfctdef.threshold, {'channel', 'range', 'artifact'}); 

cfg_artifact.mother.artfctdef.threshold.channel1 = ...                      % add both channel specifications
  cfg_artifact1.mother.artfctdef.threshold.channel;
cfg_artifact.mother.artfctdef.threshold.channel2 = ...
  cfg_artifact2.mother.artfctdef.threshold.channel;

cfg_artifact.child.artfctdef.threshold.channel1 = ...
  cfg_artifact1.child.artfctdef.threshold.channel;
cfg_artifact.child.artfctdef.threshold.channel2 = ...
  cfg_artifact2.child.artfctdef.threshold.channel;

cfg_artifact.mother.artfctdef.threshold.range1 = ...                        % add both range values
  cfg_artifact1.mother.artfctdef.threshold.range;
cfg_artifact.mother.artfctdef.threshold.range2 = ...
  cfg_artifact2.mother.artfctdef.threshold.range;

cfg_artifact.child.artfctdef.threshold.range1 = ...
  cfg_artifact1.child.artfctdef.threshold.range;
cfg_artifact.child.artfctdef.threshold.range2 = ...
  cfg_artifact2.child.artfctdef.threshold.range;

artPart1 = [ cfg_artifact1.mother.artfctdef.threshold.artifact; ...         % concatenate artifact specifications
  cfg_artifact2.mother.artfctdef.threshold.artifact ];

artPart2 = [ cfg_artifact1.child.artfctdef.threshold.artifact; ...
  cfg_artifact2.child.artfctdef.threshold.artifact ];

[~,idx] = sort(artPart1(:,1));                                              % sort values in a ascending order
artPart1 = artPart1(idx, :);

[~,idx] = sort(artPart2(:,1));
artPart2 = artPart2(idx, :);

idx       = [true; sum(diff(artPart1),2) ~= 0];                             % remove duplicates
artPart1  = artPart1(idx,:);

idx       = [true; sum(diff(artPart2),2) ~= 0];
artPart2  = artPart2(idx,:);

cfg_artifact.mother.artfctdef.threshold.artifact = artPart1;
cfg_artifact.child.artfctdef.threshold.artifact = artPart2;

cfg_artifact.bad1Num = size(...                                             % update numbers of bad channels
                    cfg_artifact.mother.artfctdef.threshold.artifact, 1);

cfg_artifact.bad2Num = size(...
                    cfg_artifact.child.artfctdef.threshold.artifact, 1);                  
end

